name: Journey
options:
  deploymentTarget:
    iOS: 15.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.journey.app
    DEVELOPMENT_TEAM: ""
    INFOPLIST_FILE: Journey/Info.plist
    SWIFT_VERSION: 5.5
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
packages: {}
targets:
  Journey:
    type: application
    platform: iOS
    sources:
      - path: Journey/Sources
      - path: Journey/Resources
        type: folder
        excludes:
          - "**/*.xcassets/**"
    resources:
      - path: Journey/Resources/Assets.xcassets
      - path: Journey/Resources/Base.lproj
    settings:
      base:
        PRODUCT_NAME: Journey
        PRODUCT_BUNDLE_IDENTIFIER: com.journey.app
        DEVELOPMENT_TEAM: ""
        INFOPLIST_FILE: Journey/Info.plist
        TARGETED_DEVICE_FAMILY: 1
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
        SWIFT_VERSION: 5.5
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
